name: Callee

on:
  workflow_call:
    inputs:
      param:
        type: string
        default: nothing
        required: false

jobs:
  callee-job:
    name: Callee Job
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "PARAM=${{ inputs.param }}"
          echo ${{ toJson(github) }}
